[project]
name = "Deep Convolutional Generative Adversarial Network - MNIST"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "pip==24.3.1",
    "numpy==2.2.3",
    "matplotlib==3.10.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
]